using System.Collections.Concurrent;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;

namespace Rkd.Scalar.OpenApi.XmlComments
{
    /// <summary>
    /// Reads the XML documentation files generated by <c>&lt;GenerateDocumentationFile&gt;true&lt;/GenerateDocumentationFile&gt;</c>
    /// at runtime, one per assembly, next to the assembly or in the application base directory.
    /// </summary>
    /// <remarks>
    /// The OpenAPI source generator of ASP.NET Core only sees <c>AddOpenApi</c> calls compiled in the
    /// application project; the calls made inside Rkd.Scalar are invisible to it. Reading the files at
    /// runtime makes XML comments work for every document without extra code.
    /// </remarks>
    internal sealed partial class XmlDocumentationProvider
    {
        private readonly ConcurrentDictionary<Assembly, IReadOnlyDictionary<string, XElement>> _files = new();

        public XmlMemberDocumentation? GetMember(MemberInfo member)
        {
            var id = XmlDocumentationId.For(member);

            if (id is null)
                return null;

            var assembly = member is Type type ? type.Assembly : member.Module.Assembly;

            return _files.GetOrAdd(assembly, Load).TryGetValue(id, out var element)
                ? new XmlMemberDocumentation(element)
                : null;
        }

        private static IReadOnlyDictionary<string, XElement> Load(Assembly assembly)
        {
            var members = new Dictionary<string, XElement>(StringComparer.Ordinal);

            var path = FindFile(assembly);

            if (path is null)
                return members;

            try
            {
                var document = XDocument.Load(path);

                foreach (var member in document.Descendants("member"))
                {
                    var name = member.Attribute("name")?.Value;

                    if (!string.IsNullOrEmpty(name))
                        members[name] = member;
                }
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or System.Xml.XmlException)
            {
                // A broken or unreadable documentation file must never break the OpenAPI document.
            }

            return members;
        }

        private static string? FindFile(Assembly assembly)
        {
            if (assembly.IsDynamic)
                return null;

            var fileName = assembly.GetName().Name + ".xml";

            var candidates = new List<string>();

            if (!string.IsNullOrEmpty(assembly.Location))
                candidates.Add(Path.ChangeExtension(assembly.Location, ".xml"));

            candidates.Add(Path.Combine(AppContext.BaseDirectory, fileName));

            return candidates.FirstOrDefault(File.Exists);
        }

        /// <summary>
        /// Converts the content of an XML documentation element into plain text.
        /// </summary>
        internal static string? ToText(XElement? element)
        {
            if (element is null)
                return null;

            var builder = new StringBuilder();
            AppendNodes(builder, element);

            var text = LineBreakRegex().Replace(builder.ToString(), "\n");
            text = SingleLineBreakRegex().Replace(text, " ");
            text = MultipleSpacesRegex().Replace(text, " ");
            text = ParagraphRegex().Replace(text, "\n\n").Trim();

            return text.Length == 0 ? null : text;
        }

        private static void AppendNodes(StringBuilder builder, XElement element)
        {
            foreach (var node in element.Nodes())
            {
                switch (node)
                {
                    case XText text:
                        builder.Append(text.Value);
                        break;

                    case XElement child:
                        AppendElement(builder, child);
                        break;
                }
            }
        }

        private static void AppendElement(StringBuilder builder, XElement element)
        {
            switch (element.Name.LocalName)
            {
                case "see":
                case "seealso":
                    if (!element.IsEmpty)
                        AppendNodes(builder, element);
                    else if (element.Attribute("langword")?.Value is { } langword)
                        builder.Append(langword);
                    else if (element.Attribute("cref")?.Value is { } cref)
                        builder.Append(ShortName(cref));
                    else if (element.Attribute("href")?.Value is { } href)
                        builder.Append(href);
                    break;

                case "paramref":
                case "typeparamref":
                    builder.Append(element.Attribute("name")?.Value);
                    break;

                case "para":
                    builder.Append("\n\n");
                    AppendNodes(builder, element);
                    builder.Append("\n\n");
                    break;

                case "br":
                    builder.Append("\n\n");
                    break;

                default:
                    AppendNodes(builder, element);
                    break;
            }
        }

        private static string ShortName(string cref)
        {
            var name = cref.Length > 2 && cref[1] == ':' ? cref[2..] : cref;

            var parenthesis = name.IndexOf('(');
            if (parenthesis >= 0)
                name = name[..parenthesis];

            var dot = name.LastIndexOf('.');
            return dot >= 0 ? name[(dot + 1)..] : name;
        }

        [GeneratedRegex(@"[ \t]*\r?\n[ \t]*")]
        private static partial Regex LineBreakRegex();

        [GeneratedRegex(@"(?<!\n)\n(?!\n)")]
        private static partial Regex SingleLineBreakRegex();

        [GeneratedRegex(@"[ \t]{2,}")]
        private static partial Regex MultipleSpacesRegex();

        [GeneratedRegex(@"\s*\n\n\s*")]
        private static partial Regex ParagraphRegex();
    }

    /// <summary>
    /// Documentation of a single member (<c>&lt;member name="..."&gt;</c>).
    /// </summary>
    internal sealed class XmlMemberDocumentation
    {
        private readonly XElement _element;

        public XmlMemberDocumentation(XElement element)
        {
            _element = element;
        }

        public string? Summary => XmlDocumentationProvider.ToText(_element.Element("summary"));

        public string? Remarks => XmlDocumentationProvider.ToText(_element.Element("remarks"));

        public string? Returns => XmlDocumentationProvider.ToText(_element.Element("returns"));

        public string? Value => XmlDocumentationProvider.ToText(_element.Element("value"));

        public string? Parameter(string name) =>
            XmlDocumentationProvider.ToText(
                _element.Elements("param").FirstOrDefault(p => p.Attribute("name")?.Value == name));

        public IEnumerable<(string Code, string? Description)> Responses =>
            _element.Elements("response")
                .Select(r => (Code: r.Attribute("code")?.Value ?? string.Empty, Description: XmlDocumentationProvider.ToText(r)))
                .Where(r => r.Code.Length > 0);
    }
}
